### ISSUE TITLE
docker 이미지 404 not found

### ISSUE THREAD

**Issue by JB0527** [DevTae/SpeechFeedback#27]
안녕하세요!

리드미에 올려주신 dockerhub 링크에 접속해도 도커이미지가 안뜨고 404오류만 떠서 이슈를 남깁니다!

감사합니다!

**Comment by DevTae** [comment]
안녕하세요.

현재 말씀주신 도커 이미지에 대해서 확인해본 결과, 아직 활성화되어 있는 것으로 확인되었습니다! [[링크]](https://hub.docker.com/r/devtae/kospeech)

`docker pull devtae/kospeech`

혹시 CLI 환경에서 위 명령어로 이미지가 끌어와지는지 테스트 가능하시나요?

감사합니다.

**Comment by JB0527** [comment]
제가 도커에 대한 지식이 부족해서 wsl 환경에선 꽤 힘드네요 ㅠㅠ 그렇지만! 그냥 아예 리눅스 기반에선 되는 것 같습니다! 감사합니다.
