### ISSUE TITLE
pretrained model이 있을까요?

### ISSUE THREAD

**Issue by JB0527** [DevTae/SpeechFeedback#30]
안녕하세요? 

학교 프로젝트로 음성인식 기능이 필요하여 kospeech를 따라해보면서 모델을 구현 해보았으나, 생각보다 성능이 따라오지 않아서 이 레포의 pretrained model이 있는가 하여 문의를 남깁니다..!!

추가로 해당 repo 등의 음성전처리 등을 보며 덕분에 공부를 많이 하였습니다.
감사합니다.!

**Comment by DevTae** [comment]
안녕하세요!

일단, 현재 해당 프로젝트에서의 모델은 `라벨 데이터를 IPA 변환한 것으로 사용`하여 STT 결과값이 한글이 나오지 않습니다.

해당 프로젝트 모델의 CER 이 약 0.12 정도가 나온다고 생각하시면 되는데, 다운로드를 희망하시면 해당 이슈에 답변을 달아주시는 이메일로 전송해드리겠습니다.

감사합니다.

**Comment by JB0527** [comment]
안녕하세요? 답이 늦어 죄송합니다..!!

관련 파일을 보내주시면 저야 너무 좋습니다!!! 어려움을 겪고 있었는데, 덕분에 잘 해결될 것 같습니다!
감사합니다.

메일주소는 qhdrl527@gmail.com 입니다.

**Comment by DevTae** [comment]
이메일로 전송 완료하였습니다. 궁금한 점 있으시면 이슈 달아주세요!

해당 이슈는 닫겠습니다.

**Comment by saeu5407** [comment]
안녕하세요. 발음 단위 한국어 모델에 관심이 있는 유저인데요. 혹시 저도 가중치파일을 받을 수 있을까요?
메일주소는 dyddl1993@gmail.com 입니다.

**Comment by sylee6529** [comment]
@DevTae 안녕하세요! 음성인식&자연어처리 모델 공부중인 대학생입니다. 올려주신 것으로 도움 많이 받았습니다.
학교 수업 과제로 따라 구현하면서 한국어 가중치파일이 필요하게 되었는데, 혹시 받아볼 수 있을까요? 

메일 주소는 sylee6529@gmail.com 입니다.

**Comment by K1A2** [comment]
안녕하세요. 비슷한 테스크를 구현중인 대학생입니다. 혹시 저도 가중치파일을 받아볼 수 있을까요?
메일주소는 jckim0307@gmail.com 입니다.
감사합니다.
