### ISSUE TITLE
현재 레포에서 실행하기 위해 필요한 파일

### ISSUE THREAD

**Issue by JB0527** [DevTae/SpeechFeedback#31]
안녕하세요? 매번 도움을 주셔서 감사합니다.

현재 레포에서 실행하기 위해 필요한 파일이 model.pt와 aihub_labels.csv 인거 같습니다.
앞선 issue에선 덕분에 model.pt 파일을 받았지만 ipa로 mapping 되어있는  aihub_labels.csv가 제게 없는 것 같습니다..!

사실 어쩌면 model 문제가 아니라 ipa로 변환시킬 mapping된 csv가 없어서 ksponspeechvocabulary 함수에서 제대로 처리 안된것 같습니다.

혹시 제 생각대로 model.pt와 mapping할 csv 파일 이 2개만 있으면 이 레포를 실행가능할 지 그리고 라벨 데이터를 IPA 변환한 것이라면 model.pt가 다른 한국어 데이터셋으로 학습되었다하더라도 사용가능할 지 궁금합니다.

계속 도움만 받는 것 같아 죄송합니다... ㅠㅠ

**Comment by DevTae** [comment]
맞습니다! 제가 aihub_labels.csv 파일을 같이 못 드렸었네요.

[aihub_labels.csv](https://github.com/DevTae/SpeechFeedback/files/15144763/aihub_labels.csv)

해당 파일로 적용하시면 될 겁니다!

**Comment by JB0527** [comment]
안녕하세요..!

덕분에 음성을 inference 파일을 통해 돌리면 speech to IPA는 가능해졌습니다.
다만 "SpeechFeedback/kospeech/bin/ipa_feedback.py", line 17을 보시면 len(ch)에서 ch가 의미하는 것이 무엇인지 궁금합니다.

도움을 주셔서 감사합니다!

**Comment by DevTae** [comment]
- 아래 사진처럼 코드 변경할 때 미처 반영되지 않은 부분이 있었네요. 코드 반영하여 올려두었습니다.
  ![image](https://github.com/DevTae/SpeechFeedback/assets/55177359/aeeb6dd2-c023-4774-bd99-583c533b3b45)

- 추가적으로, 현재 `ipa_feedback.py` 부분의 로직은 단순 탐색 방식으로 하나씩 채점하는 방식으로 되어 있어서, 앞 문자에서 조금이라도 틀린 것이 있으면 뒤 문자들에 대해서는 채점 결과조차 확인할 수 없는 상황이 발생하곤 합니다.
- 이에 대하여 `levenshtein distance 를 변형한 방식`을 활용하여 [`PronunciationEvaluator`](https://github.com/DevTae/PronunciationEvaluator) 라이브러리(전반적인 발음 채점을 위한)를 추가 개발하였는데, 현재 `SpeechFeedback` 에서는 적용되어 있지 않은 상황이라 이 부분 논의하시고 적용을 고려해보시는 것을 추천드립니다.

- 진행하시는 프로젝트 성공적으로 되시길 응원합니다!

**Comment by JB0527** [comment]
안녕하세요 큰 도움이 되었습니다! [PronunciationEvaluator](https://github.com/DevTae/PronunciationEvaluator) 특히 이 부분 덕분에 완전히 이해할 수 있었어요!! 감사합니다.

추천해주신 레포를 프로젝트 리드미에 달아놓겠습니다 감사합니다!
